---
title: "Consulting"
author: "sts"
date: "2024-10-26"
output: pdf_document
---
```{r}
library(rstanarm)
library(dplyr)
library(lme4)
```
```{r}
perception_complete<-read.csv("/Users/fengqiuyi/Downloads/Homework/MA675/consult10.2/perception_complete.csv")
```
```{r}
perception_complete$rating <- factor(perception_complete$rating, 
                            levels = sort(unique(perception_complete$rating)),  # 定义因子的水平
                            ordered = TRUE)  # 指定为有序因子

str(perception_complete)
```
```{r}
perception_complete[] <- lapply(perception_complete, function(x) {
  if (is.character(x)) {
    factor(x)  # 如果是字符型，转换为因子
  } else {
    x  # 如果不是字符型，则保持不变
  }
})

# 检查转换后的数据框结构
str(ceb_click)
```


```{r}
ceb_click <- perception_complete %>%
  filter(lang_source == "ceb", target == "click")

ceb_knock <- perception_complete %>%
  filter(lang_source == "ceb", target == "knock")

spn_click <- perception_complete %>%
  filter(lang_source == "spn", target == "click")

spn_knock <- perception_complete %>%
  filter(lang_source == "spn", target == "knock")

```




```{r}
LmerT <- lmer(rating ~ vk + (1 | speaker), data = perception_complete)
# 拟合模型
LmerCC <- lmer(rating ~ vk + (1 | speaker), data = ceb_click)
LmerCK <- lmer(rating ~ vk + (1 | speaker), data = ceb_knock)

LmerSC <- lmer(rating ~ vk + (1 | speaker), data = spn_click)
LmerSK <- lmer(rating ~ vk + (1 | speaker), data = spn_knock)

```
```{r}
library(ggplot2)

ceb_click$predicted <- predict(LmerCC)
ceb_knock$predicted <- predict(LmerCK)
spn_click$predicted <- predict(LmerSC)
spn_knock$predicted <- predict(LmerSK)
# 可视化
ggplot(ceb_click, aes(x = vk, y = rating)) +
  geom_line(aes(y = predicted), color = "black", size = 1) +  # 绘制预测线
  labs(title = "Linear Mixed Effects Model: Actual vs Predicted",
       x = "vk",
       y = "Rating") +
  scale_y_continuous(limits = c(1, 10), breaks = seq(1, 10, 1)) +
  theme_minimal()
```


```{r}

ggplot(ceb_knock, aes(x = vk, y = rating)) +
  geom_line(aes(y = predicted), color = "black", size = 1) +  # 绘制预测线
  labs(title = "Linear Mixed Effects Model: Actual vs Predicted",
       x = "vk",
       y = "Rating") +
  scale_y_continuous(limits = c(1, 10), breaks = seq(1, 10, 1)) +
  theme_minimal()
```


```{r}

ggplot(spn_click, aes(x = vk, y = rating)) +
  geom_line(aes(y = predicted), color = "black", size = 1) +  # 绘制预测线
  labs(title = "Linear Mixed Effects Model: Actual vs Predicted",
       x = "vk",
       y = "Rating") +
  scale_y_continuous(limits = c(1, 10), breaks = seq(1, 10, 1)) +
  theme_minimal()
```


```{r}

ggplot(spn_knock, aes(x = vk, y = rating)) +
  geom_line(aes(y = predicted), color = "black", size = 1) +  # 绘制预测线
  labs(title = "Linear Mixed Effects Model: Actual vs Predicted",
       x = "vk",
       y = "Rating") +
  scale_y_continuous(limits = c(1, 10), breaks = seq(1, 10, 1)) +
  theme_minimal()
```


```{r}
residuals <- resid(LmerT)
qqnorm(residuals)
qqline(residuals, col = "red", lwd = 2)  # Add a reference line
shapiro.test(residuals)
residuals <- resid(LmerCC)
qqnorm(residuals)
qqline(residuals, col = "red", lwd = 2)  # Add a reference line
shapiro.test(residuals)
residuals <- resid(LmerCK)
qqnorm(residuals)
qqline(residuals, col = "red", lwd = 2)  # Add a reference line
shapiro.test(residuals)
residuals <- resid(LmerSC)
qqnorm(residuals)
qqline(residuals, col = "red", lwd = 2)  # Add a reference line
shapiro.test(residuals)
residuals <- resid(LmerSK)
qqnorm(residuals)
qqline(residuals, col = "red", lwd = 2)  # Add a reference line
shapiro.test(residuals)
```


```{r}
# 绘制残差 vs. 拟合值的图
fitted_values <- fitted(LmerT)
residuals <- resid(LmerT)

plot(fitted_values, residuals, 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red")

fitted_values <- fitted(LmerCC)
residuals <- resid(LmerCC)

plot(fitted_values, residuals, 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red")

fitted_values <- fitted(LmerCK)
residuals <- resid(LmerCK)

plot(fitted_values, residuals, 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red")

fitted_values <- fitted(LmerSC)
residuals <- resid(LmerSC)

plot(fitted_values, residuals, 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red")

fitted_values <- fitted(LmerSK)
residuals <- resid(LmerSK)

plot(fitted_values, residuals, 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red")

```


```{r}
# 缩放残差图

# 创建数据框
df <- data.frame(Fitted = fitted(LmerCC), 
                 Scaled_Residuals = sqrt(abs(residuals(LmerCC))))

# 绘制图形
ggplot(df, aes(x = Fitted, y = Scaled_Residuals)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, color = "blue") +
  labs(title = "Scale-Location Plot",
       x = "Fitted Values",
       y = "Square Root of Standardized Residuals")

df <- data.frame(Fitted = fitted(LmerCK), 
                 Scaled_Residuals = sqrt(abs(residuals(LmerCK))))

# 绘制图形
ggplot(df, aes(x = Fitted, y = Scaled_Residuals)) +
  
  
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, color = "blue") +
  labs(title = "Scale-Location Plot",
       x = "Fitted Values",
       y = "Square Root of Standardized Residuals")

df <- data.frame(Fitted = fitted(LmerSC), 
                 Scaled_Residuals = sqrt(abs(residuals(LmerSC))))

# 绘制图形
ggplot(df, aes(x = Fitted, y = Scaled_Residuals)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, color = "blue") +
  labs(title = "Scale-Location Plot",
       x = "Fitted Values",
       y = "Square Root of Standardized Residuals")

df <- data.frame(Fitted = fitted(LmerSK), 
                 Scaled_Residuals = sqrt(abs(residuals(LmerSK))))

# 绘制图形
ggplot(df, aes(x = Fitted, y = Scaled_Residuals)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, color = "blue") +
  labs(title = "Scale-Location Plot",
       x = "Fitted Values",
       y = "Square Root of Standardized Residuals")

```


```{r}
library(ordinal)
fm1 <- clmm2(rating ~ vk, random=speaker, data=ceb_click)
pr1 <- profile(fm1, range=c(.1, 10), nSteps=30, trace=0)
plot(pr1, main="ceb_click")

fm2 <- clmm2(rating ~ vk, random=speaker, data=ceb_knock)
pr2 <- profile(fm2, range=c(.1, 10), nSteps=30, trace=0)
plot(pr2, main="ceb_knock")

fm3 <- clmm2(rating ~ vk, random=speaker, data=spn_click)
pr3 <- profile(fm3, range=c(.1, 10), nSteps=30, trace=0)
plot(pr3, main="spn_click")

fm4 <- clmm2(rating ~ vk, random=speaker, data=spn_knock)
pr4 <- profile(fm4, range=c(.1, 10), nSteps=30, trace=0)
plot(pr4, main="spn_knock")

```


```{r}
fm5 <- clmm2(rating ~ vk, random=speaker, data=perception_complete)
pr5 <- profile(fm5, range=c(.1, 10), nSteps=30, trace=0)
plot(pr5,main="all_data")
```




```{r}
ci <- fm1$ranef + qnorm(0.975) * sqrt(fm1$condVar) %o% c(-1, 1)
ord.re <- order(fm1$ranef)
ci <- ci[order(fm1$ranef),]
plot(1:length(fm1$ranef), fm1$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="ceb_click")
axis(1, at=1:length(fm1$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm1$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)

```


```{r}
ci <- fm2$ranef + qnorm(0.975) * sqrt(fm2$condVar) %o% c(-1, 1)
ord.re <- order(fm2$ranef)
ci <- ci[order(fm2$ranef),]
plot(1:length(fm2$ranef), fm2$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="ceb_knock")
axis(1, at=1:length(fm2$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm2$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)

```


```{r}
ci <- fm3$ranef + qnorm(0.975) * sqrt(fm3$condVar) %o% c(-1, 1)
ord.re <- order(fm3$ranef)
ci <- ci[order(fm3$ranef),]
plot(1:length(fm3$ranef), fm3$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="spn_click")
axis(1, at=1:length(fm3$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm3$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)

```


```{r}
ci <- fm4$ranef + qnorm(0.975) * sqrt(fm4$condVar) %o% c(-1, 1)
ord.re <- order(fm4$ranef)
ci <- ci[order(fm4$ranef),]
plot(1:length(fm4$ranef), fm4$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="spn_knock")
axis(1, at=1:length(fm4$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm4$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)

```


```{r}
fm1 <- clmm2(rating ~ vk, random=speaker, data=ceb_click)
pr1 <- profile(fm1, range=c(.1, 10), nSteps=30, trace=0)
plot(pr1, main="ceb_click_logit")
ci <- fm1$ranef + qnorm(0.975) * sqrt(fm1$condVar) %o% c(-1, 1)
ord.re <- order(fm1$ranef)
ci <- ci[order(fm1$ranef),]
plot(1:length(fm1$ranef), fm1$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="ceb_click_logit")
axis(1, at=1:length(fm1$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm1$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)

fm1 <- clmm2(rating ~ vk, random=speaker, data=ceb_click,link ="probit")
pr1 <- profile(fm1, range=c(.1, 10), nSteps=30, trace=0)
plot(pr1, main="ceb_click_probit")
ci <- fm1$ranef + qnorm(0.975) * sqrt(fm1$condVar) %o% c(-1, 1)
ord.re <- order(fm1$ranef)
ci <- ci[order(fm1$ranef),]
plot(1:length(fm1$ranef), fm1$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="ceb_click_probit")
axis(1, at=1:length(fm1$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm1$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)

fm1 <- clmm2(rating ~ vk, random=speaker, data=ceb_click,link ="loglog")
pr1 <- profile(fm1, range=c(.1, 10), nSteps=30, trace=0)
plot(pr1, main="ceb_click_loglog")
ci <- fm1$ranef + qnorm(0.975) * sqrt(fm1$condVar) %o% c(-1, 1)
ord.re <- order(fm1$ranef)
ci <- ci[order(fm1$ranef),]
plot(1:length(fm1$ranef), fm1$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="ceb_click_loglog")
axis(1, at=1:length(fm1$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm1$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)
```



```{r}
fm1 <- clmm2(rating ~ vk, random=speaker, data=ceb_click)
pr1 <- profile(fm1, range=c(.1, 10), nSteps=30, trace=0)
plot(pr1, main="ceb_click_flexible")
ci <- fm1$ranef + qnorm(0.975) * sqrt(fm1$condVar) %o% c(-1, 1)
ord.re <- order(fm1$ranef)
ci <- ci[order(fm1$ranef),]
plot(1:length(fm1$ranef), fm1$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="ceb_click_flexible")
axis(1, at=1:length(fm1$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm1$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)

fm1 <- clmm2(rating ~ vk, random=speaker, data=ceb_click,threshold="symmetric")
pr1 <- profile(fm1, range=c(.1, 10), nSteps=30, trace=0)
plot(pr1, main="ceb_click_symmetric")
ci <- fm1$ranef + qnorm(0.975) * sqrt(fm1$condVar) %o% c(-1, 1)
ord.re <- order(fm1$ranef)
ci <- ci[order(fm1$ranef),]
plot(1:length(fm1$ranef), fm1$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="ceb_click_symmetric")
axis(1, at=1:length(fm1$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm1$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)

fm1 <- clmm2(rating ~ vk, random=speaker, data=ceb_click,threshold = "equidistant")
pr1 <- profile(fm1, range=c(.1, 10), nSteps=30, trace=0)
plot(pr1, main="ceb_click_equidistant")
ci <- fm1$ranef + qnorm(0.975) * sqrt(fm1$condVar) %o% c(-1, 1)
ord.re <- order(fm1$ranef)
ci <- ci[order(fm1$ranef),]
plot(1:length(fm1$ranef), fm1$ranef[ord.re], axes=FALSE, ylim=range(ci),
     xlab="Speaker", ylab="Speaker effect",main="ceb_click_equidistant")
axis(1, at=1:length(fm1$ranef), labels = ord.re)
axis(2)
for(i in 1:length(fm1$ranef)) {
  segments(i, ci[i, 1], i, ci[i, 2])
}
abline(h = 0, lty=2)
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

